### ISSUE TITLE
Creating master frames

### ISSUE THREAD

**Issue by rprechelt** [yerkesobservatory/atlas#13]
We need a Luigi task to create/find master frames i.e.

1) Coadd all dark frames taken in the session and produce a master dark
2) Coadd all bias frames taken in the session and produce a master bias
3) Find the current master flat

**Comment by mcnowinski** [comment]
Don't know where you are with the calibration pipeline, but just in case here are a couple of Python scripts which use astropy::ccdproc. I use mastercal to create the SEO master cal frames that I have published on Slack.

https://github.com/mcnowinski/various-and-sundry/blob/master/lightcurve/calibrate.py
https://github.com/mcnowinski/various-and-sundry/blob/master/lightcurve/mastercal.py

Once again, all just ideas and perhaps just starting points...
